# Generated by Django 2.2.3 on 2021-02-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetchyoutubedata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideoapikey',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
