# Generated by Django 2.2.3 on 2023-03-05 16:40

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fetchyoutubedata', '0005_auto_20210207_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTermPublishedAfterTimestamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('published_after', models.DateTimeField(db_index=True)),
                ('search_term', models.CharField(db_index=True, max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
