version: '2.0'
services:

  redis:
    image: 'redis:3.0.6'
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/var/lib/redis/data'
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "17000m"
        max-file: "5"
    networks:
      - default

  postgres:
    image: postgres:11
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      driver: "json-file"
      options:
        max-size: "17000m"
        max-file: "5"
    networks:
      - default

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    restart: always
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - 'elasticsearch_data:/var/lib/elasticsearch/data'
    logging:
      driver: "json-file"
      options:
        max-size: "17000m"
        max-file: "5"
    environment:
      - discovery.type=single-node
    networks:
      - default

  kibana:
    image: 'kibana:7.6.0'
    restart: always
    ports:
      - '5601:5601'
    environment:
      - KIBANA_ELASTICSEARCH_URL=elasticsearch
    volumes:
      - 'kibana_data:/var/lib/kibana/data'
    depends_on:
      - elasticsearch

  api:
    build: .
    restart: always
    command: bash -c "python3 manage.py runserver 0.0.0.0:3000"
    ports:
      - '3000:3000'
    expose:
      - 3000
    environment:
      - DB_NAME=youtubevideos
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - REDIS_SERVER=redis
    networks:
      - default
    depends_on:
      - kibana
      - redis
      - postgres
      - elasticsearch

  save_latest_video_content_command:
    build: .
    restart: always
    command: bash -c "python3 manage.py savelatestvideosyoutubecommand"
    networks:
      - default
    environment:
      - DB_NAME=youtubevideos
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - REDIS_SERVER=redis
    depends_on:
      - kibana
      - redis
      - postgres
      - elasticsearch
      - api

volumes:
  redis_data:
    driver: local
  kibana_data:
    driver: local
  elasticsearch_data:
    driver: local

#networks:
#  ytdvideo:
#    name: custom_network