version: '2.0'
services:

  mysql:
    image: 'mysql:5.6'
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - 'mysql_data:/var/lib/fampay/mysql'
    logging:
      driver: json-file
      options:
        max-size: 17000m
        max-file: '5'

  redis:
    image: 'redis:3.0.6'
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/var/lib/fampay/redis/data'
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "17000m"
        max-file: "5"
    networks:
      - default

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    restart: always
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - 'elasticsearch_data:/var/lib/fampay/elasticsearch/data'
    logging:
      driver: "json-file"
      options:
        max-size: "17000m"
        max-file: "5"
    environment:
      - discovery.type=single-node
    networks:
      - default

  kibana:
    image: 'kibana:7.6.0'
    restart: always
    ports:
      - '5601:5601'
    environment:
      - KIBANA_ELASTICSEARCH_URL=elasticsearch
    volumes:
      - 'kibana_data:/var/lib/fampay/kibana/data'
    depends_on:
      - elasticsearch

  api:
    build: .
    restart: always
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:3000"
    ports:
      - '80:3000'
    environment:
      - DB_NAME=ytdvideos
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=mysql
      - DB_PORT=3306
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - REDIS_SERVER=redis
    networks:
      - default
    depends_on:
      - kibana
      - redis
      - mysql
      - elasticsearch

  save_latest_video_content_command:
    build: .
    restart: always
    command: bash -c "python3 manage.py savelatestvideosyoutubecommand"
    networks:
      - default
    environment:
      - DB_NAME=ytdvideos
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=mysql
      - DB_PORT=3306
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - REDIS_SERVER=redis
    depends_on:
      - kibana
      - redis
      - mysql
      - elasticsearch
      - api

volumes:
  redis_data:
    driver: local
  kibana_data:
    driver: local
  elasticsearch_data:
    driver: local
  mysql_data:
    driver: local
